options:
  dashboard:
    type: boolean
    default: True
    description: Deploy the Kubernetes Dashboard
  dns_domain:
    type: string
    default: cluster.local
    description: The local domain for cluster dns
